### ISSUE TITLE
The JESTr Pioneer Shield Study add-on is not uninstalled after the Firefox Pioneer add-on is removed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/jestr-pioneer-shield-study#22]
[Notes]:
- After the Firefox Pioneer add-on is removed no telemetry are sent in "about:telemetry" but the study remains installed and logs are sent in browser console. Not sure if this is a bug or it is intended.
- Not sure how telemetry works since they are encrypted for this study, but after removing the Firefox Pioneer add-on shouldn't the unenroll telemetry be sent?

[Affected Versions]:
- JESTr Pioneer Shield Study 1.2.0

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have the latest Firefox 67 unbranded build installed.
- Have the Firefox Pioneer Add-on installed.
- Have the "shieldStudy.logLevel" string pref created with "info" value.
- Have the "xpinstall.signatures.dev-root" boolean pref created with the "true" value.
- Have the JESTr Pioneer Shield Study 1.2.0 signed xpi installed.
- The browser console is opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:add-ons" > Extensions section.
3. Remove the Firefox Pioneer add-on.
4. Restart the browser, navigate to "about:support" support page and observe the "Extensions" section.
5. Verify if any telemetry pings are sent in "about:telemetry".

[Expected results]:
Step 4: The JESTr Pioneer Shield Study add-on is uninstalled and it is not displayed in the "Extensions" section.
Step 5: The unenrolled telemetry are sent.

[Actual results]:
Step 4: The JESTr Pioneer Shield Study add-on is not uninstalled and it is displayed in the "Extensions" section.
Step 5: No telemetry pings are sent.

[Additional Notes]:
- Attached a screen recording with the issue:
![after removing Firefox Pioneer](https://user-images.githubusercontent.com/19226534/59774865-d95e8980-92b8-11e9-880a-0909ea1d9c01.gif)

**Comment by motin** [comment]
A bug that hinders that mechanism has likely been fixed in [v1.2.2](https://github.com/mozilla/jestr-pioneer-shield-study/releases/tag/1.2.2), please re-test with that version of the study add-on.

> Not sure if this is a bug or it is intended.
The intention is to uninstall after a browser restart if the Pioneer opt-in is no longer active.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and it is still reproducible with the latest (jestr_pioneer_shield_study-1.2.2) signed add-on installed.
After removing the Firefox Pioneer add-on and the browser is restarted the following logs are displayed in browser console, but the JESTr Pioneer Shield Study remains installed:
![remove Firefox Pioneer](https://user-images.githubusercontent.com/19226534/59845855-0b2e2980-9367-11e9-82b2-617c5cdb6d85.png)


It seems that these logs are displayed after each Firefox restart. Also, no telemetry pings related to the study are sent in "about:telemetry" page. Tested on Windows 7 x64, Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
@motin based on the “ending study” logs displayed in browser console, shouldn't the add-on be automatically uninstalled and the specific ending telemetry pings be recorded in "about:telemetry" page?

**Comment by motin** [comment]
This has finally been fixed in [v1.2.3](https://github.com/mozilla/jestr-pioneer-shield-study/releases/tag/1.2.3), please re-test with that version of the study add-on.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using v1.2.3 version of the add-on and it seems that it is partially fixed. The study add-on is successfully uninstalled after the Firefox Pioneer add-on is removed and the browser is restarted, but no telemetry pings related to the end of the study are registered in "about:telemetry" page. 

Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.

**Comment by motin** [comment]
> but no telemetry pings related to the end of the study are registered in "about:telemetry" page.

We can definitely live with that, since we do not plan to use those pings in this particular study. Closing since the main issue has been verified fixed.
